export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    description: 'Perfect for getting started.',
    price: '₹0',
    amount: 0,
    features: ['3 reports per month', 'Basic data analysis', 'Community support'],
    priceId: null,
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Unlimited reports for serious students.',
    price: '₹499',
    amount: 499,
    period: '/month',
    features: ['Unlimited reports', 'AI report generation', 'PDF download', 'Priority support'],
    priceId: 'plan_pro', 
    popular: true,
  },
  {
    id: 'research',
    name: 'Research',
    description: 'Advanced features for researchers.',
    price: '₹4,999',
    amount: 4999,
    period: '/year',
    features: ['Unlimited reports', 'Advanced AI analysis', 'Viva preparation sheets', 'Priority processing'],
    priceId: 'plan_research',
  },
];
