import { createSupabaseServerClient } from '@/lib/supabaseServer';

export const experimentService = {
    /**
     * Creates a new experiment record in the database.
     */
    async createExperiment(data: {
        userId: string;
        title: string;
        subject?: string;
        description?: string;
        aim?: string;
        apparatus?: string;
        theory?: string;
        procedure?: string;
        result?: string;
        precautions?: string;
        conclusion?: string;
    }) {
        const supabase = await createSupabaseServerClient();

        // Add logic to save the experiment
        const { data: experiment, error } = await supabase
            .from('experiments')
            .insert({
                user_id: data.userId,
                title: data.title,
                subject: data.subject,
                description: data.description,
                aim: data.aim,
                apparatus: data.apparatus,
                theory: data.theory,
                procedure: data.procedure,
                result: data.result,
                precautions: data.precautions,
                conclusion: data.conclusion,
                status: 'completed',
                created_at: new Date().toISOString()
            })
            .select()
            .single();

        if (error) {
            console.error('Error inserting experiment:', error);
            throw new Error('Failed to create experiment in database');
        }

        return experiment;
    },

    /**
     * Fetches a specific experiment by ID for a user.
     */
    async getExperiment(experimentId: string, userId: string) {
        const supabase = await createSupabaseServerClient();

        const { data, error } = await supabase
            .from('experiments')
            .select('*')
            .eq('id', experimentId)
            .eq('user_id', userId)
            .single();

        if (error) {
            console.error('Error fetching experiment:', error);
            throw new Error('Failed to fetch experiment');
        }

        return data;
    },

    /**
     * Counts the number of experiments generated by a user.
     */
    async countUserExperiments(userId: string): Promise<number> {
        const supabase = await createSupabaseServerClient();

        const { count, error } = await supabase
            .from('experiments')
            .select('*', { count: 'exact', head: true })
            .eq('user_id', userId);

        if (error) {
            console.error('Error counting experiments:', error);
            throw new Error('Failed to count experiments');
        }

        return count || 0;
    },

    /**
     * Updates an experiment record with the generated PDF path.
     */
    async updateExperimentReportPath(experimentId: string, reportPath: string) {
        const supabase = await createSupabaseServerClient();

        const { error } = await supabase
            .from('experiments')
            .update({ report_path: reportPath })
            .eq('id', experimentId);

        if (error) {
            console.error('Error updating experiment report path:', error);
            throw new Error('Failed to update report path');
        }
    }
};
