import { NextResponse } from 'next/server';
import OpenAI from 'openai';

// Initialize the OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { experiment_title, statistics, data_summary, graph_url } = body;

    // Validate request
    if (!experiment_title || !statistics) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    if (!process.env.OPENAI_API_KEY) {
      console.error("OPENAI_API_KEY is not set.");
      return NextResponse.json(
        { error: 'OpenAI API key is not configured.' },
        { status: 500 }
      );
    }

    const prompt = `
Given the following experiment results and statistics, write clear academic lab report sections for engineering students. 
Include result interpretation, possible sources of experimental error, safety precautions, and 3 viva questions.

Experiment Title: ${experiment_title}
Data Summary: ${data_summary || 'N/A'}
Mean: ${statistics.mean}
Standard Deviation: ${statistics.std_dev}
Error Percent: ${statistics.error_percent}%
Slope: ${statistics.slope || 'N/A'}

Respond with ONLY a JSON object exactly matching this structure:
{
  "result": "...",
  "conclusion": "...",
  "error_analysis": "...",
  "precautions": "...",
  "viva_questions": ["...", "...", "..."]
}
`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini", // or gpt-4o, gpt-3.5-turbo depending on preference
      messages: [
        {
          role: "system",
          content: "You are an expert scientific writing assistant helping engineering students structure their lab reports.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      response_format: { type: "json_object" }, // Ensures OpenAI returns valid JSON
      temperature: 0.7,
    });

    const aiContent = response.choices[0]?.message?.content;

    if (!aiContent) {
      throw new Error("No content generated by OpenAI.");
    }

    const reportSections = JSON.parse(aiContent);

    return NextResponse.json(reportSections);

  } catch (error: any) {
    console.error('Error generating report:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate report' },
      { status: 500 }
    );
  }
}
