import { NextResponse } from 'next/server';
import OpenAI from 'openai';

export const dynamic = 'force-dynamic';

export async function POST(req: Request) {
  try {
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      console.error("OPENAI_API_KEY is not set.");
      return NextResponse.json(
        { error: 'OpenAI API key is not configured.' },
        { status: 500 }
      );
    }

    const body = await req.json();
    const { experiment_title, statistics, data_summary, graph_url, isDemo } = body;

    const { createSupabaseServerClient } = await import('@/lib/supabaseServer');
    const supabase = await createSupabaseServerClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user && !isDemo) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    let userData = null;
    if (user) {
      const { data } = await supabase
        .from('users')
        .select('plan, reports_count_this_month')
        .eq('id', user.id)
        .single();
      userData = data;

      if (userData?.plan === 'free' && (userData.reports_count_this_month || 0) >= 3) {
        return NextResponse.json(
          { error: 'Monthly report limit reached. Please upgrade to Pro for unlimited reports.', limit_reached: true },
          { status: 403 }
        );
      }
    }

    // Validate request
    if (!experiment_title || !statistics) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const openai = new OpenAI({ apiKey });

    const prompt = `
Given the following experiment results and statistics, write a complete academic lab report for engineering students. 
Ensure the tone is scientific and professional.

Experiment Title: ${experiment_title}
Data Summary: ${data_summary || 'N/A'}
Mean: ${statistics.mean}
Standard Deviation: ${statistics.std_dev}
Error Percent: ${statistics.error_percent}%
Slope: ${statistics.slope || 'N/A'}

Respond with ONLY a JSON object exactly matching this structure:
{
  "aim": "...",
  "apparatus": "...",
  "theory": "...",
  "procedure": "...",
  "result": "...",
  "conclusion": "...",
  "error_analysis": "...",
  "precautions": "...",
  "viva_questions": ["...", "...", "..."]
}
`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: "You are an expert scientific writing assistant helping engineering students structure their lab reports.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      response_format: { type: "json_object" },
      temperature: 0.7,
    });

    const aiContent = response.choices[0]?.message?.content;

    if (!aiContent) {
      throw new Error("No content generated by OpenAI.");
    }

    const reportSections = JSON.parse(aiContent);

    // 4. Increment usage count if it's not a demo
    if (user && !isDemo) {
      await supabase
        .from('users')
        .update({ reports_count_this_month: (userData?.reports_count_this_month || 0) + 1 })
        .eq('id', user.id);
    }

    return NextResponse.json(reportSections);

  } catch (error: any) {
    console.error('Error generating report:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate report' },
      { status: 500 }
    );
  }
}
